name: CI Prod DevFlix
run-name: CI Prod DevFlix
on:
  workflow_dispatch:
jobs:
  build:
    environment: "prod"
    name: "Build & Deploy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: "23" 
      - name: Npm Build 
        run: |
          npm install
          NODE_OPTIONS="--max-old-space-size=8192" npm run build
      - name: Upload to S3 Bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete --exclude='files/*'
        env:
          SOURCE_DIR: 'build'
          AWS_S3_BUCKET: ${{ secrets.CI_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.CI_AWS_CRED_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_AWS_CRED_SECRET }}
          AWS_REGION: ${{ secrets.CI_REGION }}
      - name: Invalidate Cloudfront - DevFlix Firefly
        uses: chetan/invalidate-cloudfront-action@master
        env:
          PATHS: '/*'
          AWS_ACCESS_KEY_ID: ${{ secrets.CI_AWS_CRED_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_AWS_CRED_SECRET }}
          AWS_REGION: ${{ secrets.CI_REGION }}
          DISTRIBUTION: ${{ secrets.CI_CLOUDFRONT_DISTRIBUTION_ID }}
      - name: Invalidate Cloudfront - DevFlix Co
        uses: chetan/invalidate-cloudfront-action@master
        env:
          PATHS: '/*'
          AWS_ACCESS_KEY_ID: ${{ secrets.CI_AWS_CRED_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_AWS_CRED_SECRET }}
          AWS_REGION: ${{ secrets.CI_REGION }}
          DISTRIBUTION: ${{ secrets.CI_CO_CLOUDFRONT_DISTRIBUTION_ID }}
